### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by uicdb** [Low-Drag-MC/Multiblocked#11]
I use this mod as lib.。
This problem occurs when I try to generate packets with runData：
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.Minecraft.getResourcePackRepository()" because the return value of "net.minecraft.client.Minecraft.getInstance()" is null
	at com.lowdragmc.multiblocked.client.ClientProxy.<init>(ClientProxy.java:23) ~[multiblocked-604054-3832169_mapped_parchment_2022.06.05-1.18.2.jar%2386!/:1.18.2-0.7] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:160) ~[fmlcore-1.18.2-40.1.51.jar%2380!/:?] {}
	at com.lowdragmc.multiblocked.Multiblocked.<init>(Multiblocked.java:71) ~[multiblocked-604054-3832169_mapped_parchment_2022.06.05-1.18.2.jar%2386!/:1.18.2-0.7] {re:classloading}
	... 14 more

**Comment by Yefancy** [comment]
yeah, it has been fixed, probably update these days

**Comment by Yefancy** [comment]
btw there is quick fix for now,
```gradle
maven {
    url "https://maven.firstdarkdev.xyz/snapshots"
}

implementation fg.deobf("com.lowdragmc.ldlib:LowDragLib:1.18.2-0.5")
implementation fg.deobf("com.lowdragmc.multiblocked:Multiblocked:1.18.2-0.8.1")
```

**Comment by uicdb** [comment]
ok，Thank you so much
